.MODEL SMALL
.STACK SIZE 100
.CODE       

MAIN PROC
    
 
MOV AH, 1       ;INPUT FUNCTON

INT 21H
MOV BL, AL      ;SCAN 1ST INPUT
          
INT 21H           
MOV CL, AL      ;SCAN 2ND INPUT 

ADD BL, CL      ;SUM METHOD (1ST + 2ND) & SUM ILL STORE IN BL REGISTER


SUB BL, 48      ;THERE IS A PROBLEM OUTPUT ILL PRINT AS HEXA VALUE, SO HAVE TO SUB. 48 FOR GETTING DECIMAL ...

            
MOV AH, 2       ;OUTPUT FUNCTON
MOV DL, BL
INT 21H         



   
     